config/routes.rb
DemoMogoid::Application.routes.draw do
  resources :users do
   member do
      get :new_profile
      put :create_profile
      get :edit_profile
      put :update_profile
    end
  end

   root :to => 'users#index'

end

app/models/profile.rb
class Profile
  include Mongoid::Document
  embedded_in :user
  field :nick_name , :type =>String
  field :phone_number  ,:type=>String
end

app/models/user.rb
class User
  include Mongoid::Document
  embeds_one :profile
  accepts_nested_attributes_for :profile
  field :name , :type =>String
  field :age  ,:type=>Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def new
   @user = User.new
  end

  def show
    @user = User.find(params[:id])
    render :json => @user
  end

  def create
    user = User.new(params[:user])
    user.save
    redirect_to root_path
  end

  def new_profile
    @user = User.find(params[:id])
    @profile = @user.build_profile
  end

  def create_profile
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    #@profile = @user.build_profile(params[:profile])
    #@profile.save
    redirect_to root_path
  end

  def edit_profile
    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def update_profile
    @user = User.find(params[:id])
    @profile = @user.profile
    @profile.update_attributes(params[:profile])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoMogoid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit_profile.html.erb
<h1>Update Profile</h1>
<%= form_for @profile,:url =>update_profile_user_path(@user) do |f|%>
    name:
    <%= f.text_field :nick_name  %>
    <%= f.text_field :phone_number  %>
    <%= f.submit %>
<%end%>

app/views/users/index.html.erb
<h1>Index Page</h1>
<%@users.each do|user| %>
<ul class = "nav">
  <li>
    <%= user.name %>
    <%= user.age %>
    <%= link_to "view", user%> ||
    <%= link_to "create profile", new_profile_user_path(user)  if user.profile.present? == false%>   ||
    <%= link_to "edit profile", edit_profile_user_path(user)  if user.profile.present? == true%>      ||
  </li>
</ul>
<%end%>

<%= link_to "new user" ,new_user_path%>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user  do |f|%>
    name:
    <%= f.text_field :name %>
    <%= f.text_field :age %>
    <%= f.submit %>
<%end%>

app/views/users/new_profile.html.erb
<h1>New Profile</h1>
<%= form_for @user,:url =>create_profile_user_path(@user) do |f|%>
    <%=f.fields_for :profile do |p| %>
    name:
    <%= p.text_field :nick_name  %>
    <%= p.text_field :phone_number  %>
    <%= f.submit %>
<%end%>
<%end%>